<?php

 $videos = array(
	array("Campeche, Vívelo para Creerlo Video promocional del Estado de Campeche", "http://www.sabancuy.com/#campeche. Campeche, Vívelo para Creerlo Video promocional del Estado de Campeche. Sabancuy esta en este precioso Estado, hoy por hoy uno de los estados con mayor crecimiento. Tienen muchas ventajas respecto a otros Estados de Mexico, una de las principales ventajas es su ubicacion geografica, cerca de Yucatan y Quintana Roo. Actualmente los 3 estados estan siendo muy visitados por turistas nacionales y extranjeros mas informacion en http://sabancuy.com/tag/campeche/", "31-05-2016 01:21:00", "Turismo", "Archivo municipal", "0", "00:31", "5", "1", "1", "abCDefgh001" , false),
	array("Campeche, que hacer en la ciudad de Campeche","Campeche es una joya que parece sacada de una novela romántica, acompáñanos a descubrir qué hacer en Campeche.", "01-06-2018 00:00:00", "Hoteles", "Hotel Carlos V", "121.00", "10:03", "1", "2", "2", "abCDefgh002", false),
	array("Campeche El Destino Consentido","Video Promocional de Campeche.", "24-05-2017 12:06:18", "Parques", "Parque de Guadalupe", "0", "07:26", "1005000", "3", "3", "abCDefgh003", false),
	array("Restaurante El Bastión, Pan de Cazón, Campeche México, Viajes y Vidas","", "20-06-2018 20:15:31", "Restaurantes", "El bastión", "1232.00", "04:39", "10520520", "4", "4", "abCDefgh004", true),
	array("Hotel Misión Campeche América Centro Histórico","Misión Campeche América Centro Histórico es un hotel de arquitectura colonial del siglo XVII ubicado en el centro histórico de la ciudad de Campeche, cerca del centro de convenciones. Aprovecha el estacionamiento gratuito y los servicios ejecutivos. Conoce nuestras ofertas en: http://www.pricetravel.com.mx/hotel-m...", "30-04-2018 01:01:17", "Hoteles", "Hotel Misión Campeche América Centro Histórico", "102.31", "03:02", "1540", "5", "5", "abCDefgh005", true),
	array("Emaya.com - Restaurante La Pigua - San Francisco de Campeche, Campeche.","La Cultura Gastronomica De Campeche Se Encuentra Definida Por Las Arraigadas Raices Que Provienen De La Deliciosa Combinacion De Su Pasado Prehispanico Y Los Mejores Sabores Del Caribe", "20-06-2018 17:32:14", "Restaurantes", "La pigua", "0", "01:22", "1000", "6", "6", "abCDefgh006", false),
	array("Actividades del parque Ximbal", "Dieron a conocer actividades que se realizaran durante las vacaciones en el parque temático de Ximbal.", "18-06-2018 17:44:55", "Parques", "Parque Ximbal", "0", "2:55", "0" , "7", "7", "abCDefgh007", false)
);